### ISSUE TITLE
Any idea why this doesn't work?

### ISSUE THREAD

**Issue by seiyria** [streamlinesocial/highcharts-regression#11]
See the demo here:
http://www.highcharts.com/plugin-registry/single/22/Highcharts%20regression

It doesn't appear to work anymore (I'm on highcharts 4.0.4).

**Comment by phpepe** [comment]
Its working now, was introduced by the last commit

**Comment by seiyria** [comment]
Thanks! Just curious, is there any way to run a regression on multiple sets of series data at once, or is it per-series only?
