### ISSUE TITLE
Linear regression does not handle missing values correctly

### ISSUE THREAD

**Issue by smaccona** [streamlinesocial/highcharts-regression#15]
When missing values (```null``` values) are included in the dataset, HighCharts correctly plots the chart but the linear regression trendline is incorrect. See this example with a missing value for "June 8":

![image](https://cloud.githubusercontent.com/assets/394952/8093328/37f9c3ae-0f8e-11e5-9d31-b57ad3c1cb62.png)

The r<sup>2</sup> value is consequently also wrong, and thus the r value is wrong too (it's not computable at all in Javascript in the example above as r<sup>2</sup> is negative).

The same dataset in other tools (e.g. Excel here) shows the correct trendline:

![image](https://cloud.githubusercontent.com/assets/394952/8093866/8266b688-0f91-11e5-8751-3f43c12aa2a0.png)

The issue here is that while the `_linear` function checks to see whether a data point is valid while iterating through the data and creating the various &Sigma; values used in the regression, the total number of data points (including invalid/missing ones) is used in the calculation of the gradient & intercept for the trendline. Similarly, the `coefficientOfDetermination` should also filter out missing values and filter out the corresponding calculations for `SSYY` and `SSE`.

This is easy to correct in the code - here is a modified output after I made the changes:

![image](https://cloud.githubusercontent.com/assets/394952/8094504/861b8b38-0f95-11e5-895a-aa26e902868f.png)

I will create a pull request with this fix.

**Comment by phpepe** [comment]
Thanks for the fix and the nice explanation !
Sure send me a merge request and I can test your solution and push to
master if works.


2015-06-10 18:24 GMT-03:00 Seamus Mac Conaonaigh <notifications@github.com>:
