### ISSUE TITLE
Enhancement: configurable decimal places in r2 and r stats

### ISSUE THREAD

**Issue by smaccona** [streamlinesocial/highcharts-regression#17]
Sometimes it's useful to display more decimal places in r<sup>2</sup> and r than the hard-coded 2 decimal places currently available:

![image](https://cloud.githubusercontent.com/assets/394952/8117769/d2314abc-1058-11e5-8b6f-a4d3921f26ee.png)

This is easily passed as a configuration option (e.g. `decimalPlaces`) in the `regressionSettings` object and can be defaulted to `2`, so that existing users will see no difference.

A related issue is that the value of `regression.rSquared` is rounded to two decimal places before it is use to calculate `regression.rValue` - this can easily lead to rounding errors in the `rValue`, so it probably makes sense to calculate the `rValue` first with the unrounded `rSquared` and then round `rSquared` to the desired number of decimal places afterwards.

I'll create a pull request with these changes/enhancements - let me know if you are OK with merging it. Thanks for a most useful library!

**Comment by phpepe** [comment]
yeah ! sounds great, send me the pull request.
Thanks for contributing to this project - I'm a bit busy at this moment,
but I will find a time to add more improvements and fixes

2015-06-11 17:43 GMT-03:00 Seamus Mac Conaonaigh <notifications@github.com>:
