### ISSUE TITLE
How do I use this in Angular2?

### ISSUE THREAD

**Issue by mikiva** [streamlinesocial/highcharts-regression#37]
I am quite new to web programming and thus new to Highcharts. We are doing a school project and are using Angular2. We can get Highcharts to work with it, but we can not find a way to implement this regression script. I'm starting to wonder if it's even possible.

Thanks

**Comment by phpepe** [comment]
Not official angular integration yet. It should work as any highcharts/angular integration http://www.highcharts.com/blog/194-using-highcharts-with-angular-js
