### ISSUE TITLE
Displaying R squared

### ISSUE THREAD

**Issue by gkruger** [streamlinesocial/highcharts-regression#38]
Hi

Thank you for a great plugin. I would like to display R squared on the chart and I found some references to it in some docs, but I cannot find the setting. Can you please help.

Gert

PS: Apologies if this is not the right approach, but I am not sure how else to make contact.

**Comment by phpepe** [comment]
Hey, Add "%r2"  to the legend and will replaced with the calculated value.
You can add the equation as well as shown in the examples.


2016-05-10 12:40 GMT-03:00 gkruger <notifications@github.com>:

**Comment by gkruger** [comment]
Thank you
