### ISSUE TITLE
highcharts-regression.js Broken

### ISSUE THREAD

**Issue by bmuscolino** [streamlinesocial/highcharts-regression#42]
Last working version:
https://raw.githubusercontent.com/streamlinesocial/highcharts-regression/b72f785422b07188fc13df0941f2aecd6b64db9c/highcharts-regression.js is the last working version. 

Example of code broken: http://www.highcharts.com/plugin-registry/single/22/Highcharts%20regression

**Comment by magaras** [comment]
It doesn't seem to be broken..

**Comment by phpepe** [comment]
Solved in 6f6beb177c8356a5fb75754dc612715de3450ea8
