### ISSUE TITLE
Question re regressionSettings:

### ISSUE THREAD

**Issue by zala143** [streamlinesocial/highcharts-regression#46]
not so much as a bug but a couple of questions relating to the possibilities within the regressionSettings: {} section.

1. is it possible to apply a custom text label similar to plotlines or series tooltips? 

I've tried format like, label: {text: 'Trend'} and title....., but that was ignored; I'm trying to provide a more friendly label that the returned "Equation: y = 0x + -445.28: 55.73" value that's showing up in the tooltip dialog box.

2. similar to above, are there options to show/render different line types, e.g. dashStyle: 'dash', from plotlines?

many thanks in advance,

**Comment by phpepe** [comment]
About the line styles, plase take a look into this example: http://jsfiddle.net/3g4ryLc9/4/
You need to add style options to the  regressionSettings object: 
```
      regressionSettings: {
        type: 'polynomial',
        color: 'rgba(223, 183, 83, .9)',
        dashStyle: 'dash'
      },
```

**Comment by phpepe** [comment]
To update the legend just add a ''name" property to the regression settings. 
See http://jsfiddle.net/3g4ryLc9/5/

**Comment by zala143** [comment]
many thanks for the quick response - i will give that a try.
