### ISSUE TITLE
Having multiple series in same scatter plot and regression line for one of the series

### ISSUE THREAD

**Issue by VivekTodur** [streamlinesocial/highcharts-regression#66]
Thanks for the nice example. I would like to add multiple series to the scatter plot but want to show regression line for only one of them. How can I achieve it...??

Thanks in advance,
Vivek

**Comment by phpepe** [comment]
I'm sorry to say that is not possible right now. There is a bug that
prevents that case, just confirmed it.
For multiple series, you can only set the regression for all series like
shown here http://jsfiddle.net/asork1nb/
Tagged this as a bug, will solve it asap.
Thanks for reporting this issue,

Ignacio Vazquez


2018-03-15 6:40 GMT-03:00 Vivek Todur <notifications@github.com>:
