### ISSUE TITLE
Module breaks addSerie()

### ISSUE THREAD

**Issue by borys-p** [streamlinesocial/highcharts-regression#81]
This module wraps `addSerie()` function, but **doesn't return a value**! It just took me about three hours of debugging to realize this. It doesn't affect standard Highcharts usage, but breaks the drilldown module, which uses the value returned by `addSeries()`.

The fix is simple, just add a `return` statement in the wrapper:
`return proceed.apply(this, Array.prototype.slice.call(arguments, 1));`

**Comment by phpepe** [comment]
Thanks ! added your fix on my last commit
