### ISSUE TITLE
Webpack import fails

### ISSUE THREAD

**Issue by slh93** [streamlinesocial/highcharts-regression#85]
Using `npm install highcharts-regression`:

`import highchartsRegression from 'highcharts-regression'`

fails.

Using `npm install https://github.com/streamlinesocial/highcharts-regression`

`import highchartsRegression from 'highcharts-regression' `

succeeds.

The code is slightly different between what is in the github repo and what has been published to npm. Can you publish the most recent version to npm to resolve this?

**Comment by phpepe** [comment]
It's ready - just published latest version on npm.
Thanks !
