### ISSUE TITLE
Uncaught TypeError: Cannot read property 'valueSuffix' of undefined 

### ISSUE THREAD

**Issue by nrduncan** [streamlinesocial/highcharts-regression#9]
On the latest change it's generating an error in the console: 
"Uncaught TypeError: Cannot read property 'valueSuffix' of undefined"

Issue is happening with all examples, ex:
http://jsfiddle.net/phpepe/3vruC/

**Comment by phpepe** [comment]
Solved in the latest version - thanks for reporting the issue
